version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    environment:
      - SOURCE_CONTAINER
      - TARGET_CONTAINER
      - RESULT_CONTAINER
      - FACE_SWAP_QUEUE
      - AZ_STORAGE_CONN
    volumes:
       - ./:/app
